package com.example.sketchy.service;

import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.UUID;
import com.google.genai.Client;
import com.google.genai.types.Content;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;

import org.springframework.beans.factory.annotation.Value;

@Service
public class GeminiService {

    @Value("${spring.ai.google.genai.api-key}")
    private String googleApiKey;

    private static final String PROMPT = "You are a master sketch artist in domain of textile that specialises in converting design of a traditional indian ladies suit from an image to a sketch template"
            + " You identify different components of the suit from the image, stating with border, then you identify the design of the neck and at last you see if there is any block pattern on the suit. The border is a repetitive pattern that marks the exterior boundary of the sketch."
            + " The neck is a vertically symmetrical design at the top of the sketch within the border that indicates the style of the suit."
            + " I will be giving you an image. You have to identify the textile suit in the image, extract it and convert it to a sketch template following the same style as I described.";

    public byte[] processImageWithGemini(MultipartFile image) throws IOException {
        if (image == null || image.isEmpty()) {
            throw new IllegalArgumentException("Image file is empty or missing");
        }

        Path tempFilePath = null;
        try {
            String uploadDir = "src/main/resources/static";
            File dir = new File(uploadDir);
            if (!dir.exists()) {
                dir.mkdirs();
            }

            String fileName = UUID.randomUUID().toString() + "_" + image.getOriginalFilename();
            tempFilePath = Paths.get(uploadDir, fileName);
            Files.copy(image.getInputStream(), tempFilePath, StandardCopyOption.REPLACE_EXISTING);

            byte[] imageBytes = image.getBytes();
            String mimeType = image.getContentType() != null ? image.getContentType() : "image/png";
            System.out.println("<<<<<<<<<>>>>>>>>>>>>>");
            try (Client client = Client.builder().apiKey(googleApiKey).build()) {
                System.out.println("111111111111111");
                GenerateContentConfig config = GenerateContentConfig.builder()
                        .responseModalities("TEXT", "IMAGE")
                        .build();
                System.out.println("222222222222222");
                GenerateContentResponse response = client.models.generateContent(
                        "gemini-3.1-flash-image-preview",
                        Content.fromParts(
                                Part.fromText(PROMPT),
                                Part.fromBytes(imageBytes, mimeType)),
                        config);
                System.out.println("333333333333333");
                // Extract the generated image from response parts
                for (Part part : response.parts()) {
                    if (part.inlineData().isPresent()) {
                        var blob = part.inlineData().get();
                        if (blob.data().isPresent()) {
                            return blob.data().get();
                        }
                    }
                }

                // If no image was returned, fall back to original
                System.out.println("No image generated by Gemini. Text response: " + response.text());
                return imageBytes;
            }
        } finally {
            if (tempFilePath != null) {
                try {
                    Files.deleteIfExists(tempFilePath);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
