spring.application.name=sketchy
spring.config.import=optional:file:.env[.properties]

spring.ai.google.genai.project-id=${GOOGLE_GENAI_PROJECT_ID}
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
